name: MyShopPlugin
version: '${project.version}'
main: com.maks.myshopplugin.MyShopPlugin
api-version: '1.20'
commands:
  shop:
    description: Opens the main shop GUI with service options.
    usage: /shop
    permission: shopplugin.use
  smelter:
    description: Opens the item smelter GUI.
    usage: /smelter
    permission: shopplugin.smelter
  checklore:
    description: Displays the lore of the item in hand.
    usage: /checklore
    permission: shopplugin.checklore

